# Generated by Django 6.0.3 on 2026-05-17 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_skill_userskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='value',
            field=models.PositiveSmallIntegerField(default=5, help_text='Оценка от 1 до 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
